proton-j/src/main/java/org/apache/qpid/proton/engine/impl/TransportImpl.java
proton-j/src/main/java/org/apache/qpid/proton/engine/impl/TransportLink.java
tests/python/proton_tests/engine.py

Link attach, detach, attach sequence on single session did not result
in a new link being established for the 2nd attach, it was just quietly
ignored.

PROTON-154: proton-j attach same link on a session

---

contrib/proton-hawtdispatch/src/main/java/org/apache/qpid/proton/hawtdispatch/impl/AmqpTransport.java

Remove one of calls to transport.connecting() as this causes
an assert with SslTransport

PROTON-838: proton-hawtdispatch cannot connect with SSL

---

proton-j/src/main/java/org/apache/qpid/proton/engine/impl/TransportImpl.java

As discussed on the mailing list. Currently proton-j advertises a
provided local idle timeout value as-is, whereas proton-c will halve it
before sending it to the remote side. The two implementations should
match in behaviour.

PROTON-843: Java should match C for idle timeout

---

proton-j/src/main/java/org/apache/qpid/proton/engine/impl/TransportImpl.java
proton-j/src/main/java/org/apache/qpid/proton/engine/impl/TransportSession.java

* when receiving an attach with a handle > handle-max, the connection
should be closed
* when attempting to allocate a new local handle when handle-max are
already in-use should throw an Exception
* the default of 1024 handle-max is quite small when proton-c appears to
default to 4294967295 - increase it more modestly to 65536
Closes #16

PROTON-844: police handle-max in proton-j

---

proton-c/CMakeLists.txt
proton-c/bindings/CMakeLists.txt
proton-c/bindings/python/cproton.i
proton-c/bindings/python/proton/__init__.py
proton-c/include/proton/connection.h
proton-c/include/proton/cproton.i
proton-c/include/proton/event.h
proton-c/include/proton/sasl.h
proton-c/include/proton/transport.h
proton-c/src/engine/engine-internal.h
proton-c/src/engine/engine.c
proton-c/src/events/event.c
proton-c/src/messenger/messenger.c
proton-c/src/reactor/acceptor.c
proton-c/src/reactor/connection.c
proton-c/src/sasl/cyrus_sasl.c
proton-c/src/sasl/none_sasl.c
proton-c/src/sasl/sasl-internal.h
proton-c/src/sasl/sasl.c
proton-c/src/ssl/openssl.c
proton-c/src/tests/reactor.c
proton-c/src/transport/transport.c
proton-j/src/main/java/org/apache/qpid/proton/engine/impl/SaslImpl.java
proton-j/src/main/resources/csasl.py
tests/python/proton_tests/sasl.py
tests/python/proton_tests/transport.py

This work Adds some new APIs to the transport and connection
objects to make a higher level abstraction for authentication.
This generally makes it much easier to use authentication.
It also vastly changes the Proton C API for SASL and deprecates
nearly all of the previous interface that allowed reading and
writing individual SASL frames.

PROTON-334: SASL Implementation for Proton-C using Cyrus SASL

---

.gitattributes
bin/export.sh

+ allow specific tag to be specified as cmdline arg
+ confirm the tag exists before proceeding
+ use the version.txt from that tag as the tar prefix folder
+ re-run the version.sh script before packaging to ensure the correct
version is set
+ add .gitattributes to exclude .gitignore files from the exported tar
Closes #28

NO-JIRA: improvements to export.sh

---

proton-j/src/main/java/org/apache/qpid/proton/reactor/Reactor.java
proton-j/src/main/java/org/apache/qpid/proton/reactor/impl/AcceptorImpl.java
proton-j/src/main/java/org/apache/qpid/proton/reactor/impl/IO.java
proton-j/src/main/java/org/apache/qpid/proton/reactor/impl/IOHandler.java
proton-j/src/main/java/org/apache/qpid/proton/reactor/impl/IOImpl.java
proton-j/src/main/java/org/apache/qpid/proton/reactor/impl/ReactorImpl.java
proton-j/src/main/java/org/apache/qpid/proton/reactor/impl/SelectorImpl.java
proton-j/src/test/java/org/apache/qpid/proton/reactor/ReactorTest.java
proton-j/src/test/java/org/apache/qpid/proton/reactor/impl/AcceptorImplTest.java
proton-j/src/test/java/org/apache/qpid/proton/reactor/impl/LeakTestReactor.java

This implements an interface which is similar to pn_io - so that the various Java I/O resources (e.g. Selector, Pipe, SocketChannel, and ServerSocketChannel) are all created in a single place.  
The new IO interface is used by a new test class: LeakTestReactor to extend ReactorImpl with logic for detecting when a Java I/O resource is _not_ closed by a testcase.
The Reactor unit tests have been parameterized to run once with the reactor implementation returned from Proton.reactor() and once with the LeakTestReactor test class.

PROTON-881: make unittests check for Java I/O object leaks

---

proton-j/src/main/java/org/apache/qpid/proton/engine/Link.java
proton-j/src/main/java/org/apache/qpid/proton/engine/impl/LinkImpl.java

The Link detached state is required to assess when a
LINK_REMOTE_DETACHED event is received as to whether or not it was as a
result of a local detach or the remote end detaching or closing the
link.

PROTON-931: proton-j expose detached state of Link

---

proton-c/bindings/python/proton/__init__.py
proton-c/include/proton/session.h
proton-c/src/engine/engine-internal.h
proton-c/src/engine/engine.c
proton-c/src/transport/transport.c
proton-j/src/main/java/org/apache/qpid/proton/engine/Session.java
proton-j/src/main/java/org/apache/qpid/proton/engine/impl/SessionImpl.java
proton-j/src/main/java/org/apache/qpid/proton/engine/impl/TransportImpl.java
proton-j/src/main/java/org/apache/qpid/proton/engine/impl/TransportSession.java
proton-j/src/main/resources/cengine.py
tests/python/proton_tests/engine.py

As discussed on the mailing lists [1], proton currently sets the outgoing window to 0 in most cases (except when using Messenger), but then sends messages anyway if allowed by the current remote-outgoing-window. This means it is typically violating the advertised window. Additionally, Service Bus uses the outgoing window to initialise its incoming window, which means it is set to 0 and we can never send it any messages.
This is an initial attempt at an update based on the discussions. It sets the outgoing window to a fixed default value of max int, and adds a setter to allow users of the engine to adjust it. Mainly looking for feedback on the approach and whether I have committed any atrocities on the C/python side, as I basically cut and paste all of those changes after grep'ing use of …

PROTON-936 session outgoing window handling

---

.travis.yml

This is specifically for comment from @dnwe -  I'm proposing to change the travis build config to use containers, but I've stopped using the existng jenkins build script.
This does make the travis CI builds start almost immediately for me, so is a big win in my experience.

NO-JIRA: Change travis configuration to use container based builds

---

examples/python/tx_recv_interactive.py

This pull request should fix the tx_recv_interactive.py example.

PROTON-1139 tx_recv_interactive.py example doesn't work

---

proton-c/bindings/javascript/CMakeLists.txt

Attempting to build Proton with Emscripten on the path fails with the following
message:
/home/prestona/git/qpid-proton/examples/c/messenger/recv-async.c:26:10: fatal
error: 'pncompat/misc_funcs.inc' file not found
#include "pncompat/misc_funcs.inc"
^
1 error generated.
This appears to have been introduced by commit
84e416e389fe74ec7a1cab9252af2342fc95b83f

NO-JIRA: Fix break in Javascript bindings build

---

proton-j/src/main/java/org/apache/qpid/proton/codec/ArrayType.java
proton-j/src/main/java/org/apache/qpid/proton/codec/BinaryType.java
proton-j/src/main/java/org/apache/qpid/proton/codec/ByteBufferDecoder.java
proton-j/src/main/java/org/apache/qpid/proton/codec/DecoderImpl.java
proton-j/src/main/java/org/apache/qpid/proton/codec/ListType.java
proton-j/src/main/java/org/apache/qpid/proton/codec/MapType.java

In #readValue() for ArrayType, BinaryType, ListType and MapType
decoding, if the 'count' specified is very large then it is likely to
trigger an OutOfMemoryException. As these can come from an external data
source, during the SASL init for example, there is a potential for a
denial of service. The fix is to throw an IllegalArgumentException if
the count value is larger than the amount of data available in the
received bytes.

PROTON-1249: Safeguard type initialisations.

---

proton-j/src/main/java/org/apache/qpid/proton/amqp/transport/ReceiverSettleMode.java
proton-j/src/main/java/org/apache/qpid/proton/amqp/transport/SenderSettleMode.java
proton-j/src/main/java/org/apache/qpid/proton/message/impl/MessageImpl.java
proton-j/src/test/java/org/apache/qpid/proton/amqp/transport/ReceiverSettleModeTest.java
proton-j/src/test/java/org/apache/qpid/proton/amqp/transport/SenderSettleModeTest.java

Refactored ReceiverSettleMode and SenderSettleMode for having trivial casting from/to UnsignedByte
Added message annotations to the String visualization of AMQP message

[PROTON-1352] Trivial casting from UnsignedByte to SenderSettleMode and ReceiverSettleMode

---

proton-c/bindings/cpp/include/proton/default_container.hpp

Changes
- Add warnings for default_container.hpp, function.hpp, url.hpp, and some methods in value.hpp
- Removed some deprecated type conversion functions that were never published as API
- Convert examples that used the URL class to instead split the connection URL and address into two args
- Some minor example improvements
Notes and questions
- This approach requires users define PN_CPP_USE_DEPRECATED_API if they want to carry on without moving to the preferred APIs.
- The alternative is #pragma message (just a warning), but that's not as portable as #error.  #warning is regrettably non-standard.
- I'm using #define PN_CPP_USE_DEPRECATED_API/#undef for internal uses - what's the other approach?  I remember a recommendation to use an ORed set of internal variables, but I unfortunately …

PROTON-1369: Add deprecation warnings to the C++ binding

---

c/include/proton/sasl.h
c/src/sasl/sasl.c

Small change that fixes a pain point if you have kerberos on you client machine but aren't using it for proton.
The SASL handling is changed so that if you want to use kerberos you now need to tell the pn_sasl_allowed_mechs() API on the client that you allow GSSAPI and/or GSS-SPNEGO mechanisms (along with any other mechanisms you want).
The logic here is that you are very unlikely to want GSSAPI unless you have specifically set it up and then you will know that and can allow it specifically.
[edited for the amended PR]

PROTON-1354: Don't allow SASL mechanisms GSSAPI or GSS-SPNEGO by default

---

c/src/core/codec.c
c/src/core/transport.c
c/tests/data.c
c/tests/test_tools.h
python/tests/proton_tests/engine.py

AMQP spec allows several ways to encode a "multiple" field, we allow all in
incoming data or pn_data_t values created in the user, but when writing
to the wire we always encode:
- empty array as null
- single value array as a single value
- multiple values - encoded as array
This is the most compact encoding and seems to be best for interop, as some AMQP
clients (.NET) have trouble with an empty array in a multiple value field.

PROTON-1940: [c] normalize encoding of multiple="true" fields

---

.travis.yml

Tried a few different updates to rectify the [travis xcode7.3 build failure](https://travis-ci.org/apache/qpid-proton/jobs/436640885) with this having the least impact. Originally we needed this to get a working python version but now we don't and the upgrade to 3.7.0 breaks pip for the moment.

NO-JIRA: Removed python upgrade for xcode7.3 travis build to fix pip issue

---

c/tools/reactor-recv.c

dead_error_line: Execution cannot reach the expression 0UL inside this statement: *actual = (buf ? needed : 0...

NO-JIRA: [c] Fix "Logically dead code" warning caused by excessive NULL checks

---

c/src/proactor/libuv.c

This is a clang-analyzer warning, and it does look suspicious. Consider this more like a suspected bug report (diff makes it easier to explain than verbal description) than a fix.
> Result of 'calloc' is converted to a pointer of type 'pn_netaddr_t', which is incompatible with sizeof operand type 'lsocket_t'
CC @alanconway @astitcher

NO-JIRA: [c] Fix typo in sizeof (wrong, bigger, type used)

---

c/examples/send-ssl.c

CID 214944 (#1 of 1): Missing break in switch (MISSING_BREAK)unterminated_case: The case for value
PN_CONNECTION_REMOTE_OPEN is not terminated by a 'break' statement.
This looks genuinely wrong. Either there is `break` missing, or there should be some `/* fallthrough */` comment to signal this is intentional.

NO-JIRA: [c] missing break in send-ssl.c example

---

python/proton/_reactor.py
python/tests/proton_tests/connect.py

According to the [documentation](https://github.com/apache/qpid-proton/blob/master/docs/connect-config.md), default port should be `amqps`.

PROTON-2109: [Python] Correct default JSON schema to amqps

---

c/src/sasl/sasl.c

Temporary measure before the issue is fully addressed. This allows more qpid-dispatch tests to pass on macOS.

PROTON-2122: Increase hardcoded limit from 16 to 32 SASL mechanisms

---

c/tests/fdlimit.py

Otherwise, when setting both the soft and hard limit it may fail with
prlimit: failed to set the NOFILE resource limit: Operation not permitted

PROTON-2115 Set only the soft process limit in fdlimit test

---

c/CMakeLists.txt
c/include/proton/logger.h
c/include/proton/transport.h
c/src/compiler/gcc/start.c
c/src/compiler/msvc/start.c
c/src/core/codec.c
c/src/core/connection_driver.c
c/src/core/dispatcher.c
c/src/core/engine-internal.h
c/src/core/init.c
c/src/core/init.h
c/src/core/log.c
c/src/core/logger.c
c/src/core/logger_private.h
c/src/core/transport.c
c/src/proactor/epoll.c
c/src/proactor/libuv.c
c/src/proactor/win_iocp.c
c/src/sasl/cyrus_sasl.c
c/src/sasl/sasl.c
c/src/ssl/openssl.c
c/src/ssl/schannel.c
c/tests/fuzz/fuzz-connection-driver.c
python/setup.py.in
python/tests/proton_tests/transport.py

See [PROTON-2131](https://issues.apache.org/jira/browse/PROTON-2131) for some of the problems this API seeks to solve.
This change
- Introduces a new type ```pn_logger_t``` which represents a logger
- The library has a default logger this can be retrieved using ```pn_default_logger()```
All new loggers will inherit their properties from the default logger at the point they are created. The default logger will also be used for any messages logged outside the context of an AMQP connection.
- In the current proton code every ```pn_transport_t``` object also has a logger, which will be initialised from the default logger when the transport is created. All messages logged in the context of an AMQP connection will be logged to the connection's transport's logger.
The transport's logger can be …

PROTON-2131: Introduce new proton logging API

---

c/include/proton/proactor.h
c/include/proton/transport.h
c/src/core/engine-internal.h
c/src/core/transport.c
c/src/proactor/epoll.c
c/src/proactor/libuv.c
c/src/proactor/win_iocp.c

- deprecates pn_proactor_now in favour of new pn_proactor_now_64
- replaces use of pn_i_now2 with pn_proactor_now_64
- uses GetTickCount64() in iocp proactor, instead of GetSystemTimeAsFileTime

PROTON-2030 Use CLOCK_MONOTONIC in proactors for pn_transport_tick

---

c/tests/fuzz/fuzz-connection-driver.c

I completely forgot about this one. Maybe when it is fixed, the fuzz target will not be crashing so much and the OSS Fuzz infra will run it more.

PROTON-2136 Fix fuzz-connection-driver to be tolerant of NULL input buffer

---

.travis.yml

This is the minimal change that seems to resolve this.
I have another PR which uses the addons:homebrew:packages feature in .travis.yml, but making any larger change to dependencies on macOS seems to be a tarpit full of issues so far to me.

PROTON-2147 on xcode10.1, openssl is in opt/openssl@11/, not in opt/openssl/

---

.travis.yml

Maybe use addons:homebrew:packages on xcode10.1 where it is easy, and leave it the way it is on xcode8.3.

PROTON-2147 use addons:homebrew:packages feature in .travis.yml for xcode10.1

---

c/CMakeLists.txt
c/include/proton/cid.h
c/include/proton/logger.h
c/src/core/buffer.c
c/src/core/codec.c
c/src/core/engine.c
c/src/core/error.c
c/src/core/logger.c
c/src/core/memory.c
c/src/core/memory.h
c/src/core/object/iterator.c
c/src/core/object/list.c
c/src/core/object/map.c
c/src/core/object/object.c
c/src/core/object/record.c
c/src/core/object/string.c
c/src/core/transport.c
c/src/core/util.c
c/src/core/util.h
c/tests/fuzz/CMakeLists.txt

This code is preliminary code to allow tracking of memory use in proton-c by class of memory object being used.
It tracks the various classes of memory allocated by proton-c - the number of allocations/deallocation & sizes of these for each individual memory class.
It tracks separately the memory used in the object instances themselves - direct memory and memory allocated in variable buffers by the objects - indirect memory use. For some classes of memory the direct/indirect distinction is not that clear and this code does the best it can without undue overhead.
This system is attached to the newly introduced logging system and memory usage stats will be dumped using the logger on program exit. Details appear in the DEBUG level and the summary in the INFO level. The application can …

Memory usage tracking for proton-c

---

c/tests/fuzz/CMakeLists.txt

* [c] prefer linking with static library in fuzz tests
* [c] link fuzzing binaries using CXX linker
this supersedes https://github.com/apache/qpid-proton/pull/146 and https://github.com/apache/qpid-proton/pull/143

PROTON-2078: Upstream c/test/fuzz patches from oss-fuzz

---

.travis.yml

Without the test excludes, these are the failures in logs
ruby:
```
30: /Users/travis/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': incompatible library version - /Users/travis/build/jdanekrh/qpid-proton/build/ruby/cproton.bundle (LoadError)
30: 	from /Users/travis/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
30: 	from /Users/travis/build/jdanekrh/qpid-proton/ruby/lib/qpid_proton.rb:19:in `<top (required)>'
30: 	from /Users/travis/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
30: 	from /Users/travis/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
30: 	from /Users/travis/build/jdanekrh/qpid-proton/ruby/tests/test_tool …
```

PROTON-2167 Upgrade macOS images in .travis.yml and exclude failing ruby and python tests

---

c/src/ssl/schannel.c

When execution gets to `server_name_matches` in `schannel.c`, an attempt is made to deallocate a chunk of memory here: https://github.com/apache/qpid-proton/blob/0.30.0/c/src/ssl/schannel.c#L2078
However, this is incorrect because the code is passing the pointer's address (which is a memory location on the stack, not the heap) to LocalFree . This causes a crash. The fix is simply to pass the pointer's value: https://github.com/attila-kun/qpid-proton/commit/21e88fe0b18a4587768b16ae275a8ae88fd919bb

PROTON-2194 Fix for incorrect memory deallocation

---

cpp/src/container_test.cpp

Calling listen() with invalid address is not supposed to throw a C++ exception, it is supposed end up calling the `on_error` callback. So let's remove the try catch blocks from the test, since there aren't any expected exceptions here.

PROTON-1675 [cpp] Attempt to listen on invalid URL will not throw exception

---

go/pkg/amqp/message.go

When using this library in an application to receive messages from QPID, we found our containers were getting OOM killed in kubernetes. 
This fixes the memory leak we uncovered.

PROTON-2200 Fix memory leak in go message unmarshal

---

.travis.yml
c/tests/CMakeLists.txt
tests/tsan.supp
tests/valgrind.supp

@astitcher Can you please help me figure out why is this failing on Windows (AppVeyor)? I cannot even identify the cause in the error ouptut. (Link here, or one of the previous builds at https://ci.appveyor.com/project/jirkadanek/qpid-proton/builds/33002940)

PROTON-2225: enable threaderciser by default, suppress race checkers

---

python/tests/integration/test_PROTON_1800_syncrequestresponse_fd_leak.py

@astitcher this implements the decorator you suggested to skip test if `AssertionError`s occurred.

PROTON-1800: issue not completely fixed, ignore the failing test

---

python/tests/integration/test_PROTON_1800_syncrequestresponse_fd_leak.py
python/tests/integration/test_PROTON_2121_blocking_connection_fd_leak.py

Python context managers propagate thrown exceptions out of their `yield` statement.
If the test broker is to be always stopped, a finally block is necessary.

PROTON-2220 fix cleanup in test_broker @contextmanager

---

c/src/core/encoder.c
c/tests/data_test.cpp

All tests pass.
It appears necessary to test for both pn_is_in_array() && pn_is_first_in_array(), using only the latter causes failures in the list tests.

PROTON-2244: Fix for Array of lists with first list empty encoding

---

.travis.yml
c/tests/CMakeLists.txt

This should make `ctest --timeout` work like in qpid-dispatch. CC @ChugR

PROTON-2270 remove explicit threaderciser timeout; set a global one for Travis

---

CMakeLists.txt
c/CMakeLists.txt
cpp/CMakeLists.txt
go/CMakeLists.txt

This seems to be working, but I'll want to test it more, if I forgot anything. It was suspiciously easy to accomplish.

PROTON-2171: Add BUILD_EXAMPLES option, to optionally skip building examples

---

.github/workflows/build.yml

This is mainly tp avoid the broken 1.15.3 which is default on macOS.

PROTON-2295 avoid broken Go 1.15.3 on macOS CI

---

ruby/spec/message_spec.rb

I strongly dislike using random numbers in tests in this particular manner. I'd have much preferred doing a simple
```ruby
@message.ttl = -1
```
That would be a perfectly clear and understandable test for this boundary condition, in my view.
However, this is not something I am ready to go on a crusade about, at least not right now.

PROTON-2281 Fix flakiness in ruby-message-spec test

---

python/proton/_handlers.py

I assume this is just a type, since the line above stated `auto_accept` and the parameter as well.

NO-JIRA: [doc] fix auto_accept typo

---

.appveyor.yml
.github/workflows/build.yml
.travis.yml
CMakeLists.txt
c/CMakeLists.txt
c/tests/CMakeLists.txt
python/CMakeLists.txt
tests/examples/CMakeLists.txt
tools/cmake/Modules/CheckPythonModule.cmake
tools/cmake/Modules/FindPython.cmake

Use https://cmake.org/cmake/help/git-stage/module/FindPython.html
There is few issues with doing this
* branching on CMake version is bad practice
* PYTHON_EXECUTABLE can be specified from outside, this changes user API (depending on CMake version)
* Travis CI apparently uses CMake 3.12 (on all Ubuntu versions); can be upgraded

PROTON-2217 Prefer first working Python on PATH, prefer Py3 over Py2

---

c/src/proactor/epoll-internal.h

Build with epoll proactor on musl is broken since at least version 0.23.0 and
https://github.com/apache/qpid-proton/commit/37136940e3077f25ce58c94775f48c66f666f4a8
because musl does not define PTHREAD_MUTEX_ADAPTIVE_NP resulting in the
following build failure:
In file included from /home/giuliobenetti/autobuild/run/instance-0/output-1/build/qpid-proton-0.33.0/c/src/proactor/epoll.c:60:
/home/giuliobenetti/autobuild/run/instance-0/output-1/build/qpid-proton-0.33.0/c/src/proactor/epoll-internal.h: In function 'pmutex_init':
/home/giuliobenetti/autobuild/run/instance-0/output-1/build/qpid-proton-0.33.0/c/src/proactor/epoll-internal.h:319:36: error: 'PTHREAD_MUTEX_ADAPTIVE_NP' undeclared (first use in this function); did you mean 'PTHREAD_MUTEX_STALLED'?
319 | …

PROTON-2346: c/src/proactor/epoll-internal.h: fix build on musl

---

cpp/include/proton/link.hpp
cpp/include/proton/receiver_options.hpp
cpp/include/proton/sender_options.hpp
cpp/src/container_test.cpp
cpp/src/link.cpp
cpp/src/receiver_options.cpp
cpp/src/sender_options.cpp

In C++ API, allow setting of link properties via sender and receiver options
Allow query of link properties set by remote end
Add tests

PROTON-2332: [C++] Allow access to link properties

---

c/CMakeLists.txt

epoll proactor unconditionally uses pthread.h which will result in the
following build failure:
[  3%] Building C object c/CMakeFiles/qpid-proton-proactor-objects.dir/src/proactor/epoll.c.o
In file included from /nvme/rc-buildroot-test/scripts/instance-0/output-1/build/qpid-proton-0.33.0/c/src/proactor/epoll.c:60:
/nvme/rc-buildroot-test/scripts/instance-0/output-1/build/qpid-proton-0.33.0/c/src/proactor/epoll-internal.h:37:10: fatal error: pthread.h: No such file or directory
37 | #include <pthread.h>
|          ^~~~~~~~~~~
To fix this failure, the user could use -DPROACTOR=none but it also
fails on:
CMake Error at c/CMakeLists.txt:481 (add_library):
Error evaluating generator expression:
$<TARGET_OBJECTS:qpid-proton-proactor-objects>
Objects of target "qpid-proton-proactor-objects" …

PROTON-2355: Fix build with -DPROACTOR=none

---

c/CMakeLists.txt

This goes back to `$<BOOL:${HAS_PROACTOR}>` This generator expression is supported even in old CMake https://cmake.org/cmake/help/v2.8.12/cmake.html#command:add_compile_options. Unless there are better ideas?

PROTON-2355: Fix CMake 2.8.12 incompatibility in the original fix

---

.travis.yml
CMakeLists.txt
tools/cmake/Modules/FindPython.cmake

Not immediately useful in Proton. This is to keep the module in sync with Dispatch code where it is duplicated.

PROTON-2323 Propagate requested version from FindPython to FindPythonInterp

---

c/tests/CMakeLists.txt

This is needed on RHEL 7, which defaults to -std=c++03, causing compilation failure.

PROTON-2389 Add COMPILE_FLAGS for test_main.cpp

---

CMakeLists.txt
c/CMakeLists.txt
c/src/ProtonConfig.cmake.in

This supersedes #312 and allows building static Dispatch on CentOS 7.
* Build Proton with `-DCMAKE_POSITION_INDEPENDENT_CODE=ON -DBUILD_STATIC_LIBS=ON -DBUILD_BINDINGS=OFF -DCMAKE_INSTALL_PREFIX=install`
* Build Dispatch with `-DProton_DIR=qpid-proton/build/install/lib64/cmake/Proton -DProton_USE_STATIC_LIBS=ON`
This version will be hopefully upstreamable.

PROTON-2254 Use more modern CMake install machinery for better config.cmake

---

cpp/src/node_options.cpp
cpp/src/target.cpp

- node_options.cpp includes both `#include "proton/codec/vector.hpp"` and  `#include "proton/types.hpp"` 
- `#include "proton/types.hpp"` includes proton types used to represent AMQP types and thus already consist `#include "proton/codec/vector.hpp"`
- Note: node_options.cpp also needs `#include "proton/codec/map.hpp"` which is being covered by types.hpp file.
- target.cpp includes `#include "proton_bits.hpp"` twice.

NO-JIRA Remove header duplicacy in node_options.cpp and target.cpp

---

python/proton/_data.py
python/proton/_delivery.py
python/proton/_events.py
python/proton/_handlers.py
python/proton/_io.py
python/proton/_reactor.py

This started as https://issues.apache.org/jira/browse/PROTON-2407
Today, I tried using qpid-proton at HEAD and I haven't found any weird PyCharm warnings caused by the annotations. I mostly used Dispatch tests as examples of user-written programs. There was one annoyance: The time handlers scheduled with `reactor.schedule()` now have to be subclasses of `proton.Handler`, in order to pass typecheck, to not be highlighted in annoying yellow. Other than that, it looked OK.
I tried running mypy on qpid-proton (https://issues.apache.org/jira/browse/PROTON-2453), but that did not go well, regarding 'internal consistency' of the type annotations. One thing that I noticed and am repairing here is the `socket.socket` mistake that I made before.
To tell the truth, I am not sure what the best next …

PROTON-2453 fix socket.socket type annotations and add more types

---

INSTALL.md

CMake variable names are case-sensitive and so `-Dproactor` doesn't work, fix that.
Also, rephrase the section a bit and mention packages required for libuv usage.

NO-JIRA: Fix and improve docs regarding libuv usage

---

.travis.yml

Xenial is over 5 years old now - I don't think we need to make sure we build on it any longer.

Update Travis CI to stop using Xenial and use Focal instead

---

c/src/messenger/store.c
c/src/messenger/transform.c
c/src/platform/platform.c
c/src/proactor/epoll.c
c/src/proactor/libuv.c
c/src/reactor/io/windows/iocp.c
c/src/reactor/io/windows/selector.c
c/src/reactor/reactor.c
c/tools/include/pncompat/internal/getopt.c
c/tools/msgr-common.c

It appears I missed some functions the first time, https://github.com/jiridanek/skupper-router/actions/runs/4513086648/jobs/7947437700#step:19:90

PROTON-2691: Additional fixes -Wstrict-prototypes compile warning from Clang

---

python/proton/_handlers.py
python/tests/proton_tests/reactor.py

When links/sessions/connections are remotely closed then locally closed the on_xxx_closed event should still fire. The existing code only fires this event for local then remote close.
This is the continuation of #323

PROTON-2401: [Python] on_xxx_closed should be called on locally closed after remote close

---

cpp/examples/flow_control.cpp

Some for loops just silently scream to be let out as while
```
[ 83%] Building CXX object cpp/examples/CMakeFiles/tracing_server.dir/tracing_server.cpp.o
/home/jdanek/repos/qpid/qpid-proton/cpp/examples/flow_control.cpp:65:18: error: variable 'i' set but not used [-Werror,-Wunused-but-set-variable]
for (int i = sequence; available && s.credit() > 0; i++) {
^
1 error generated.
```

PROTON-2715: remove unused for-cycle counter variable

---

ci/otel.sh

Fix build for https://github.com/apache/qpid-proton/commit/1ad098c0703276f7a013a16b208f2af4fd86f993.
With the recent tracing changes with OT 1.9.1, the opentelemetry build succeed but the proton build failed at cmake configuration, here [build#763](https://github.com/apache/qpid-proton/actions/runs/5089577302/jobs/9147379969#step:11:60)

Fix build for jaeger to otlp tracing changes

---

.github/workflows/build.yml

Fix deprecation warning.
```
CMake Warning at CMakeLists.txt:165 (message):
WITH_OTLP is deprecated and will be removed in future.  Please set either
WITH_OTLP_GRPC or WITH_OTLP_HTTP, or even both.
```
https://github.com/apache/qpid-proton/actions/runs/5121286125/jobs/9208853897#step:10:205

Remove 'continue' workaround for otel buiild

---

python/ext_build.py

Sort input file list so that `_cproton.cpython-310-x86_64-linux-gnu.so` builds in a reproducible way in spite of non-deterministic filesystem readdir order
See https://reproducible-builds.org/ for why this is good.
This patch was done while working on reproducible builds for openSUSE.

NO-JIRA: Sort input file list

---

c/include/proton/annotations.h
c/src/sasl/cyrus_sasl.c

The motivation is again composite build with skupper-router, which enables a warning on this function cast.

PROTON-2772: add compiler warning management macros

---

CMakeLists.txt

Follow-up to fix incorrect fix from
* https://github.com/apache/qpid-proton/pull/415

PROTON-2786: Handle check_language(CXX) more correctly

---

c/src/core/codec.c

We've also hit the bug of the Go library that is described in PROTON-2785. This bug happens when one large message is sent and another message with arbitrary size gets marshaled. 
Reason is that the large message does multiple calls with a too small message size to `pn_data_encode` which leads to the error `PN_OVERFLOW` to be set in `pn_encoder_encode` on the data field until a large enough buffer is provided. As the `pn_message_t` is reused the error hits the second message encoding.
Relevant Go code:
https://github.com/apache/qpid-proton/blob/9fdc19c53ea92254d9f4d5f7ff1809ed6f953503/go/pkg/amqp/message.go#L378-L393
Relevant C code:
https://github.com/apache/qpid-proton/blob/9fdc19c53ea92254d9f4d5f7ff1809ed6f953503/c/src/core/encoder.c#L395-L409
This PR adds clearing the error field when …

PROTON-2785: Fix pn_data_clear not clearing error

---

python/CMakeLists.txt
python/pyproject.toml

As far as I can tell, the python binding is properly typed. In order to allow using tools like mypy, it is required to have a py.typed file in the package (see PEP 561).

PROTON-2848: [Python] Add py.typed marker to package for PEP 561

---

go/pkg/electron/electron_test.go
go/pkg/electron/receiver.go

Deliveries can not be settled after the receiver has been freed. The current Go implementation leads to a segmentation fault when the receiver is closed before a delivery is acknowledged.
Therefore, this adds a check to ensure that the receiver was not closed (which ensures that `Free` has not been called on the link yet). Additionally, this changes to use `InjectWait` in order to be able to use the newly returned error.

PROTON-2843: [Go] Fix segfault with acknowledging a message on closed receiver
